#!/bin/bash
echo "🔐 SSL Certificate Setup Helper"
echo "==============================="
echo ""
echo "This script will help you create the SSL certificate files."
echo ""
echo "1. Copy your Cloudflare Origin Certificate (including -----BEGIN CERTIFICATE----- and -----END CERTIFICATE-----)"
echo "2. Save it as nginx/ssl/uat.familycart.app.crt"
echo ""
echo "3. Copy your Cloudflare Private Key (including -----BEGIN PRIVATE KEY----- and -----END PRIVATE KEY-----)"
echo "4. Save it as nginx/ssl/uat.familycart.app.key"
echo ""
echo "Example commands:"
echo "nano nginx/ssl/uat.familycart.app.crt  # Paste certificate here"
echo "nano nginx/ssl/uat.familycart.app.key  # Paste private key here"
echo ""
echo "Then run: chmod 600 nginx/ssl/uat.familycart.app.key"
echo "         chmod 644 nginx/ssl/uat.familycart.app.crt"
