name: Bug Report
description: Report a bug or issue with the application
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        
  - type: input
    id: environment
    attributes:
      label: Environment
      description: Where did you encounter this bug?
      options:
        - Production (familycart.app)
        - UAT (uat.familycart.app)
        - Development (local)
      default: 0
    validations:
      required: true
      
  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true
      
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true
      
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe what should happen...
    validations:
      required: true
      
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior  
      description: What actually happened
      placeholder: Describe what actually happens...
    validations:
      required: true
      
  - type: dropdown
    id: browsers
    attributes:
      label: Browser
      description: Which browser are you using?
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Mobile Chrome
        - Mobile Safari
        - Other
    validations:
      required: true
      
  - type: dropdown
    id: device-type
    attributes:
      label: Device Type
      description: What device are you using?
      options:
        - Desktop
        - Tablet
        - Mobile Phone
        - Other
    validations:
      required: true
      
  - type: input
    id: screen-resolution
    attributes:
      label: Screen Resolution
      description: Your screen resolution (e.g., 1920x1080, 375x667)
      placeholder: "1920x1080"
      
  - type: textarea
    id: error-messages
    attributes:
      label: Error Messages
      description: Any error messages you see (console errors, toast messages, etc.)
      placeholder: Paste error messages here...
      
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Add screenshots to help explain your problem
      placeholder: Drag and drop images here or paste image URLs...
      
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Low - Minor issue, workaround available
        - Medium - Noticeable issue, affects some functionality
        - High - Major issue, affects core functionality
        - Critical - Blocks essential functionality, requires immediate fix
    validations:
      required: true
      
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context about the problem
      placeholder: Add any other context about the problem here...
