"""fix_unit_relationship_foreign_key

Revision ID: 0a2113921588
Revises: ef912aabcc42
Create Date: 2025-07-18 15:23:34.130764

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0a2113921588"
down_revision: Union[str, Sequence[str], None] = "ef912aabcc42"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, "item", "unit", ["quantity_unit_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "item", type_="foreignkey")
    # ### end Alembic commands ###
