"""Add standardized_name and translations to Item model

Revision ID: 1aa3bd94a6b5
Revises: 2ebcd4b137e2
Create Date: 2025-06-27 08:40:36.252738

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1aa3bd94a6b5"
down_revision: Union[str, Sequence[str], None] = "2ebcd4b137e2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "item", sa.Column("standardized_name", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "item",
        sa.Column(
            "translations", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("item", "translations")
    op.drop_column("item", "standardized_name")
    # ### end Alembic commands ###
