"""Add icon_name and translations to category model

Revision ID: 2ebcd4b137e2
Revises: 4fb56a654813
Create Date: 2025-06-27 07:06:48.538942

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2ebcd4b137e2"
down_revision: Union[str, Sequence[str], None] = "4fb56a654813"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
