"""Add icon_name and translations to category model

Revision ID: 4fb56a654813
Revises: 687785059f62
Create Date: 2025-06-27 07:00:26.934065

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4fb56a654813"
down_revision: Union[str, Sequence[str], None] = "687785059f62"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "category", sa.Column("icon_name", sa.String(length=50), nullable=True)
    )
    op.add_column(
        "category",
        sa.Column(
            "translations", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("category", "translations")
    op.drop_column("category", "icon_name")
    # ### end Alembic commands ###
