"""add_foreign_key_constraint_to_quantity_unit_id

Revision ID: 795e7e423f03
Revises: 0a2113921588
Create Date: 2025-07-18 15:25:55.908684

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "795e7e423f03"
down_revision: Union[str, Sequence[str], None] = "0a2113921588"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add foreign key constraint to quantity_unit_id
    op.create_foreign_key(
        "fk_item_quantity_unit_id",
        "item",
        "unit",
        ["quantity_unit_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove foreign key constraint from quantity_unit_id (if it exists)
    try:
        op.drop_constraint("fk_item_quantity_unit_id", "item", type_="foreignkey")
    except Exception:
        pass  # Constraint doesn't exist, that's OK
    # ### end Alembic commands ###
