"""Add nickname column to user table

Revision ID: 7f96d9c28e64
Revises: b9398919b7f1
Create Date: 2025-06-26 10:25:27.310684

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7f96d9c28e64"
down_revision: Union[str, Sequence[str], None] = "b9398919b7f1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add nickname column to user table."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("nickname", sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Remove nickname column from user table."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "nickname")
    # ### end Alembic commands ###
