"""update_timezone_aware_datetime_functions

Revision ID: d7b15d135da2
Revises: 0a3a8c5bc835
Create Date: 2025-06-26 11:48:07.751540

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d7b15d135da2"
down_revision: Union[str, Sequence[str], None] = "0a3a8c5bc835"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
