"""Add structured quantity and unit table

Revision ID: ef912aabcc42
Revises: 3f5e49c141c0
Create Date: 2025-07-18 14:30:28.308112

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ef912aabcc42"
down_revision: Union[str, Sequence[str], None] = "3f5e49c141c0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "unit",
        sa.Column("id", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("symbol", sa.String(length=10), nullable=False),
        sa.Column("category", sa.String(length=20), nullable=False),
        sa.Column("base_unit", sa.String(length=20), nullable=True),
        sa.Column(
            "conversion_factor", sa.Numeric(precision=15, scale=6), nullable=True
        ),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("locale", sa.String(length=10), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "item",
        sa.Column("quantity_value", sa.Numeric(precision=10, scale=3), nullable=True),
    )
    op.add_column(
        "item", sa.Column("quantity_unit_id", sa.String(length=20), nullable=True)
    )
    op.add_column(
        "item", sa.Column("quantity_display_text", sa.String(length=100), nullable=True)
    )

    # Populate units table with standard units
    from sqlalchemy import table, column, String, Boolean, Numeric

    unit_table = table(
        "unit",
        column("id", String),
        column("name", String),
        column("symbol", String),
        column("category", String),
        column("base_unit", String),
        column("conversion_factor", Numeric),
        column("is_default", Boolean),
        column("locale", String),
    )

    # Insert standard units
    op.bulk_insert(
        unit_table,
        [
            # COUNT Units
            {
                "id": "piece",
                "name": "piece",
                "symbol": "pc",
                "category": "count",
                "base_unit": None,
                "conversion_factor": None,
                "is_default": True,
                "locale": None,
            },
            {
                "id": "pieces",
                "name": "pieces",
                "symbol": "pcs",
                "category": "count",
                "base_unit": None,
                "conversion_factor": None,
                "is_default": False,
                "locale": None,
            },
            {
                "id": "item",
                "name": "item",
                "symbol": "item",
                "category": "count",
                "base_unit": None,
                "conversion_factor": None,
                "is_default": False,
                "locale": None,
            },
            {
                "id": "items",
                "name": "items",
                "symbol": "items",
                "category": "count",
                "base_unit": None,
                "conversion_factor": None,
                "is_default": False,
                "locale": None,
            },
            {
                "id": "pack",
                "name": "pack",
                "symbol": "pack",
                "category": "count",
                "base_unit": None,
                "conversion_factor": None,
                "is_default": False,
                "locale": None,
            },
            {
                "id": "packs",
                "name": "packs",
                "symbol": "packs",
                "category": "count",
                "base_unit": None,
                "conversion_factor": None,
                "is_default": False,
                "locale": None,
            },
            {
                "id": "bottle",
                "name": "bottle",
                "symbol": "bottle",
                "category": "count",
                "base_unit": None,
                "conversion_factor": None,
                "is_default": False,
                "locale": None,
            },
            {
                "id": "bottles",
                "name": "bottles",
                "symbol": "bottles",
                "category": "count",
                "base_unit": None,
                "conversion_factor": None,
                "is_default": False,
                "locale": None,
            },
            {
                "id": "can",
                "name": "can",
                "symbol": "can",
                "category": "count",
                "base_unit": None,
                "conversion_factor": None,
                "is_default": False,
                "locale": None,
            },
            {
                "id": "cans",
                "name": "cans",
                "symbol": "cans",
                "category": "count",
                "base_unit": None,
                "conversion_factor": None,
                "is_default": False,
                "locale": None,
            },
            {
                "id": "box",
                "name": "box",
                "symbol": "box",
                "category": "count",
                "base_unit": None,
                "conversion_factor": None,
                "is_default": False,
                "locale": None,
            },
            {
                "id": "boxes",
                "name": "boxes",
                "symbol": "boxes",
                "category": "count",
                "base_unit": None,
                "conversion_factor": None,
                "is_default": False,
                "locale": None,
            },
            {
                "id": "bag",
                "name": "bag",
                "symbol": "bag",
                "category": "count",
                "base_unit": None,
                "conversion_factor": None,
                "is_default": False,
                "locale": None,
            },
            {
                "id": "bags",
                "name": "bags",
                "symbol": "bags",
                "category": "count",
                "base_unit": None,
                "conversion_factor": None,
                "is_default": False,
                "locale": None,
            },
            # WEIGHT Units
            {
                "id": "g",
                "name": "gram",
                "symbol": "g",
                "category": "weight",
                "base_unit": "g",
                "conversion_factor": 1,
                "is_default": True,
                "locale": None,
            },
            {
                "id": "kg",
                "name": "kilogram",
                "symbol": "kg",
                "category": "weight",
                "base_unit": "g",
                "conversion_factor": 1000,
                "is_default": False,
                "locale": None,
            },
            {
                "id": "lb",
                "name": "pound",
                "symbol": "lb",
                "category": "weight",
                "base_unit": "g",
                "conversion_factor": 453.592,
                "is_default": False,
                "locale": "US",
            },
            {
                "id": "oz",
                "name": "ounce",
                "symbol": "oz",
                "category": "weight",
                "base_unit": "g",
                "conversion_factor": 28.3495,
                "is_default": False,
                "locale": "US",
            },
            # VOLUME Units
            {
                "id": "ml",
                "name": "milliliter",
                "symbol": "ml",
                "category": "volume",
                "base_unit": "ml",
                "conversion_factor": 1,
                "is_default": True,
                "locale": None,
            },
            {
                "id": "l",
                "name": "liter",
                "symbol": "l",
                "category": "volume",
                "base_unit": "ml",
                "conversion_factor": 1000,
                "is_default": False,
                "locale": None,
            },
            {
                "id": "dl",
                "name": "deciliter",
                "symbol": "dl",
                "category": "volume",
                "base_unit": "ml",
                "conversion_factor": 100,
                "is_default": False,
                "locale": None,
            },
            {
                "id": "cl",
                "name": "centiliter",
                "symbol": "cl",
                "category": "volume",
                "base_unit": "ml",
                "conversion_factor": 10,
                "is_default": False,
                "locale": None,
            },
            {
                "id": "fl_oz",
                "name": "fluid ounce",
                "symbol": "fl oz",
                "category": "volume",
                "base_unit": "ml",
                "conversion_factor": 29.5735,
                "is_default": False,
                "locale": "US",
            },
            {
                "id": "cup",
                "name": "cup",
                "symbol": "cup",
                "category": "volume",
                "base_unit": "ml",
                "conversion_factor": 236.588,
                "is_default": False,
                "locale": "US",
            },
            {
                "id": "pint",
                "name": "pint",
                "symbol": "pt",
                "category": "volume",
                "base_unit": "ml",
                "conversion_factor": 473.176,
                "is_default": False,
                "locale": "US",
            },
            {
                "id": "quart",
                "name": "quart",
                "symbol": "qt",
                "category": "volume",
                "base_unit": "ml",
                "conversion_factor": 946.353,
                "is_default": False,
                "locale": "US",
            },
            {
                "id": "gallon",
                "name": "gallon",
                "symbol": "gal",
                "category": "volume",
                "base_unit": "ml",
                "conversion_factor": 3785.41,
                "is_default": False,
                "locale": "US",
            },
            # LENGTH Units
            {
                "id": "m",
                "name": "meter",
                "symbol": "m",
                "category": "length",
                "base_unit": "m",
                "conversion_factor": 1,
                "is_default": True,
                "locale": None,
            },
            {
                "id": "cm",
                "name": "centimeter",
                "symbol": "cm",
                "category": "length",
                "base_unit": "m",
                "conversion_factor": 0.01,
                "is_default": False,
                "locale": None,
            },
            {
                "id": "mm",
                "name": "millimeter",
                "symbol": "mm",
                "category": "length",
                "base_unit": "m",
                "conversion_factor": 0.001,
                "is_default": False,
                "locale": None,
            },
            {
                "id": "ft",
                "name": "foot",
                "symbol": "ft",
                "category": "length",
                "base_unit": "m",
                "conversion_factor": 0.3048,
                "is_default": False,
                "locale": "US",
            },
            {
                "id": "in",
                "name": "inch",
                "symbol": "in",
                "category": "length",
                "base_unit": "m",
                "conversion_factor": 0.0254,
                "is_default": False,
                "locale": "US",
            },
        ],
    )

    # Migrate existing quantity data
    connection = op.get_bind()

    # Update existing items: if quantity is a simple number, convert to structured format
    connection.execute(
        sa.text(
            """
        UPDATE item 
        SET 
            quantity_value = CASE 
                WHEN quantity ~ '^[0-9]+(\.[0-9]+)?$' THEN quantity::DECIMAL
                ELSE NULL 
            END,
            quantity_unit_id = CASE 
                WHEN quantity ~ '^[0-9]+(\.[0-9]+)?$' THEN 'piece'
                ELSE NULL 
            END,
            quantity_display_text = CASE 
                WHEN quantity ~ '^[0-9]+(\.[0-9]+)?$' THEN NULL
                ELSE quantity 
            END
        WHERE quantity IS NOT NULL
    """
        )
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("item", "quantity_display_text")
    op.drop_column("item", "quantity_unit_id")
    op.drop_column("item", "quantity_value")
    op.drop_table("unit")
    # ### end Alembic commands ###
